name: Testing sepa
on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0']
        phpunit-versions: ['latest']

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: xml
        coverage: xdebug
        tools: phpcs, phpunit, composer, cs2pr
      env:
        update: true

    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist
      
    - name: Validate composer.json
      run: composer validate --strict

    - name: Run phpcs
      run: phpcs -q --standard=PSR12 --report=checkstyle src | cs2pr

    - name: Run Tests
      run: phpunit --coverage-text

    - name: Send code coverage report to Codecov.io
      env:
        CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
      run: bash <(curl -s https://codecov.io/bash) || true
